# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to use for build and test'
        required: false
        default: "testing"
        type: string
    secrets:
      DOPPLER_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          cache-dependency-path: "**/*.sum"
      - name: Fetch Doppler Secrets
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
      - name: Build Go app
        env:
          BITLY_ACCESS_TOKEN: ${{ steps.doppler.outputs.BITLY_ACCESS_TOKEN }}
          PORT: ${{ steps.doppler.outputs.PORT }}
          SENTRY_DSN: ${{ steps.doppler.outputs.SENTRY_DSN }}
        run: go build -v ./...