name: Create Release

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - release/*
  pull_request:
    tags:
      - '*'
    branches:
      - main


jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: production
    secrets: inherit
  sentry-release:
    runs-on: ubuntu-latest
    needs: build
    name: Create Sentry Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Get latest tag
        id: getTag
        run: echo "GIT_TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - run: echo "SENTRY_LOG_LEVEL=debug" >> $GITHUB_ENV
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ env.GIT_TAG_NAME }}