name: Go Test Reporter

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      - development

jobs:
  report-test:
    runs-on: ubuntu-latest
    name: Report Tests
    needs: build
    steps:
      - name: List files
        run: "ls -al"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          environment: testing
          secrets: inherit
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-report
      - name: Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            junit.xml