name: Go Test Reporter

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      - develop

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: testing
    secrets: inherit
  report-test:
    runs-on: ubuntu-latest
    name: Report Tests
    needs: build
    steps:
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-report
      - name: DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: go
          coverage-file: cover.out
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
      - name: Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}