name: Test Go

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          environment: testing
          secrets: inherit